### ISSUE TITLE
"Awaiting Approval"

### ISSUE THREAD

**Issue by CanadaGeeseSuck** [FSVAOS/VAOS#127]
Even when user status is set to **1** user status shows as "Awaiting Approval."

**Comment by BossOfGames** [comment]
Display Bug. What version is this? 1.0.3a?

**Comment by CanadaGeeseSuck** [comment]
Yep, 1.0.3a

**Comment by BossOfGames** [comment]
Is this on the table or on the account page itself? Pics plz

**Comment by CanadaGeeseSuck** [comment]
On the domain.com/admin/users page:

![hk7bvtbyrikwf9sicdxcsa](https://user-images.githubusercontent.com/34501139/34457831-97c584fc-ed72-11e7-8d2b-9f2db95bc2ce.png)

All user status and admin are set to "1" in the database.

**Comment by BossOfGames** [comment]
Page is being rebuilt. Fixed in 2.0
