### ISSUE TITLE
UserControl php still not working Can't change Members Access

### ISSUE THREAD

**Issue by Woody1459** [FSVAOS/VAOS#129]
Try to change members access to give him Admin and errors                                               SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'admin' cannot be null (SQL: update `vaos_users` set `pilotid` = , `status` = 1, `admin` = , `updated_at` = 2017-12-31 06:06:10 where `id` = 13)

Actually can;t even edit there Name and it errors

Have to go into Mysql database and change manually 

Taylor can you look at code

**Comment by BossOfGames** [comment]
Fixed in 2.0
