### ISSUE TITLE
Missing Airport 

### ISSUE THREAD

**Issue by vatsaf7** [FSVAOS/VAOS#131]
Airport FAOA Ondangwa Airport is missing - this causes issues with schedule creation

**Comment by BossOfGames** [comment]
Sorry for taking so long to reply to this issue. I am rebuilding the VAOS website right now to allow for people to modify the main airport database (will be highly useful for when we implement gates into the system). This should be fixed before the end of the month.

**Comment by BossOfGames** [comment]
Revisiting the issue, The airport ICAO has been changed to FYOA on all records plus the main airport database. I am now going to close the issue.
