### ISSUE TITLE
Database migrations seem to point to a nonexistant class

### ISSUE THREAD

**Issue by Bsalarius** [FSVAOS/VAOS#138]
Installing VAOS on a blank Ubuntu server, the setup fails. Further testing seems to indicate that this is due to [line 43 of the /install route](https://github.com/FSVAOS/VAOS/blob/master/app/Http/Controllers/Admin/InstallController.php#L43). Running `php artisan migrate` results in the following output:
```
$ php artisan migrate
Migration table created successfully.


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class '104Update' not found


```

This would seem to be simply a typo, as there is a class `Update104`, however I cannot find the occurence of this typo.

Hope this helps!

```
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by BossOfGames** [comment]
What version is this? 1.0.3a? 2.0.0b2 is being released today, which resolves this. New schema.

**Comment by Bsalarius** [comment]
I was lazy and just `git clone`'d the repository... (master branch, latest)

Also, from the laravel.log file:
```
[2018-08-22 16:37:43] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class '104Update' not found in /home/va/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:410
```
not sure if that helps at all!

**Comment by Bsalarius** [comment]
I can confirm having `git checkout 2.0dp1` that it works as expected.

**Comment by BossOfGames** [comment]
Just a heads up since it's going to be relevant. You will need to drop your entire db between dp1 and b2. There's a few schema fixes I back edited in the migration files.
