### ISSUE TITLE
[SH] Modules Not Found Exception

### ISSUE THREAD

**Issue by mrsaminus** [FSVAOS/VAOS#143]
got a file error on setup for shared hosting
https://pastebin.com/3rWPuG5P

**Comment by BossOfGames** [comment]
Traced the issue back to

https://github.com/nWidart/laravel-modules/issues/283

Do you have SSH access to your shared hosting to run a few composer commands? I need a `composer dump-autoload`

**Comment by BossOfGames** [comment]
Fixed Code issues. Will be available in new zip file.
