### ISSUE TITLE
Problems Installing on Fresh Server

### ISSUE THREAD

**Issue by wppatrickk** [FSVAOS/VAOS#159]
Hello,

I am installing this on Ubuntu 16.0 with nginx/1.10.3 (Ubuntu), mysql 5.7.23 and PHP 7.1.20 with php-fpm enabled.

Here's the link to the info file http://149.56.91.84/info.php

I even reach the part where it says "'Well, welcome to your new system, or we would normally say that. So if you are seeing this message, your webserver dependencies should be in line and everything is working. There's just one problem."

But when I click on "Install", it goes to 404 not found? Is this project still being maintained?

http://149.56.91.84/setup

Thanks.

**Comment by BossOfGames** [comment]
Double check to see if you have the server rewrite enabled.

```
# Add index.php to the list if you are using PHP
        index index.html index.htm index.php;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ /index.php$is_args$args;
        }

        # pass PHP scripts to FastCGI server
        #
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                # With php-fpm (or other unix sockets):
                fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
```

**Comment by BossOfGames** [comment]
Admin panel is being fixed in overhaul. If you want to try some new code at your discretion, pull in the weekly snapshots. Hit me up on Discord directly and I can walk you through everything. https://discord.gg/KJTynEz
