### ISSUE TITLE
Still looping

### ISSUE THREAD

**Issue by RKillinger37** [FSVAOS/VAOS#172]
Hi,

New to VAOS and love the look. Was able to get it installed, but even though it says you fixed the loop because of Identicon, I still seem to be loopsing no matter what menu I choose in admin and clicking on setting wants to take me to charts.html. I do have the latest release. Any help would be appreciated.

Also, pilot side seems to work fine.

Thanks.

**Comment by BossOfGames** [comment]
Check the commits recently. I just fixed it. Download the latest files and let me know if you’re still having problems.

**Comment by BossOfGames** [comment]
Ok I forgot to push up a single file (the story of my life). Download the source files from the latest release, or just replace this file in `resources/views/layouts`
[admin2.blade.php.zip](https://github.com/FSVAOS/VAOS/files/3553752/admin2.blade.php.zip)

**Comment by RKillinger37** [comment]
Hi, I replaced the file using your instructions. Still same issue. Here's a youtube link to a short recording I did clicking on the admin links. https://youtu.be/qkJl2w4v09g

As you may see, the browser icon on the tab continues to rotate, the links go nowhere or to a blank page or to a The Content You Were Looking For Was Not found page. Also the Settings and Modules link want to point to a charts.html page.

**Comment by RKillinger37** [comment]
Hi, I replaced the file using your instructions. Still same issue. Here's a youtube link to a short recording I did clicking on the admin links. https://youtu.be/ktNI1tgfICo
Sorry about the blurryness. It's clear when I record, but youtube loves to not make things clear.

As you may see, the browser icon on the tab continues to rotate, the links go nowhere or to a blank page or to a The Content You Were Looking For Was Not found page. Also the Settings and Modules link want to point to a charts.html page.
