### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gugaua** [FSVAOS/VAOS#24]
Do you need someone who points out all "issues" in Beta?

**Comment by BossOfGames** [comment]
The staff and I have been keeping an internal list of "show stoppers" that are being resolved right now for the 1.0 RC Update.

**Comment by gugaua** [comment]
Are you sure you need someone for bug hunting?
Nobody writes back...

**Comment by BossOfGames** [comment]
Are you referring to the open issues? If so, they have been marked on our list of things to deal with. Those features were not implemented yet or not implemented properly.
