### ISSUE TITLE
Adminpanel > PIREPs > Overview

### ISSUE THREAD

**Issue by gugaua** [FSVAOS/VAOS#26]
All you can see is "[]"
![admin-pireps](https://cloud.githubusercontent.com/assets/18068098/22561456/985759bc-e978-11e6-88be-226f75849d7d.JPG)

**Comment by BossOfGames** [comment]
Returning JSON from Controller instead of GUI. Forgot to change something in the files.

**Comment by BossOfGames** [comment]
Fixed the issue in Beta 4. Will be published soon.
