### ISSUE TITLE
Recaptcha no captcha testing on VAOS

### ISSUE THREAD

**Issue by XiRealizeX** [FSVAOS/VAOS#35]
Self assigned.

**Comment by BossOfGames** [comment]
What's this?

**Comment by XiRealizeX** [comment]
![img_1375](https://cloud.githubusercontent.com/assets/20001932/23891547/ded980a6-088e-11e7-9562-6ffb485db207.PNG)
![img_1376](https://cloud.githubusercontent.com/assets/20001932/23891546/ded6d400-088e-11e7-84c6-d8aa2fcc771c.PNG)
