### ISSUE TITLE
Support for HHVM?

### ISSUE THREAD

**Issue by mcalsada** [FSVAOS/VAOS#37]
Is VAOS expected to work with HHVM? When attempting to install (and using the base NGINX configuration noted in #36) VAOS is responding to the routing events ok. The /setup works and prompts for database information. After the first prompt for mysql db information and initial VA information, the .env file format is updated to include key/value pairs containing a large number of quotes (that is inconsistent with each setting).

    APP_KEY=""""""""base64:EV5xsZUDKJzx6YYxBo6s9To5....................""""""""
    APP_DEBUG=""""""""false""""""""
    APP_LOG_LEVEL=""""""""warning""""""""
    DB_CONNECTION=""""""""mysql""""""""
    DB_HOST=""""""""127.0.0.1""""""""
    DB_PORT=""""""""3306""""""""
    DB_DATABASE=""""test_vaos""""
    DB_USERNAME="""vaos"""

After submitting these details the URL will look like: `https://vaossite/setup?mode=settings`. The page displays "Whoops, looks like something went wrong."

At this point both the setup and main home controller result in the same behavior showing the "Whoops" error. Changing the "APP_DEBUG" to true has no affect on the display. There are also no error logs being generated in hhvm or nginx to better indicate the issue.

**Comment by BossOfGames** [comment]
The installer looks to be extremely buggy. I would recommend just editing the values manually. We use a Laravel .env editor I want to deprecate and get rid of. That should fix the problem.
