### ISSUE TITLE
pilots can add the same shedule to his bid page

### ISSUE THREAD

**Issue by MrDalle** [FSVAOS/VAOS#50]
i dont know if its a bug but maybe the system should check if the pilot already has bid the flight?..

![73ef5e8ea1feacece8caa3b68cee85d9](https://cloud.githubusercontent.com/assets/7756672/25316319/1480212e-2865-11e7-9ecf-464a77ceb861.png)

**Comment by BossOfGames** [comment]
Not exactly a bug. There is no checking involved just yet. If it was to throw database errors when doing so, that would be a bug.

I will look into implementing a check which you can turn on via the settings which should prevent this.

**Comment by MrDalle** [comment]
Ok cool!

Another idea is to limt the shedule and planes when a pilot is choosing his flight etc..
So if a pilot is in VA X he can only see shedules and planes from his VA X. But Pilots in VA Y cant see the stuff from VA X... etc.. 

By having multiple VA´s and many pilots in the system its really annoying browsing thourgh the same shedule and planes just from different VA´s..

**Comment by BossOfGames** [comment]
I will be building in the above feature request into FS Hub as it basically requires that functionality.
