### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Corse-eSports** [FSVAOS/VAOS#52]
Hello ,
Can someone help me with the installation ?

Unfortunaly my host doesnt provide access to .git , I tried to install manual but doesnt work .

Can someone help me?

Cheers
Rafael Letras

**Comment by BossOfGames** [comment]
Use the Shared Hosting Package under releases. Contains everything you need.

**Comment by Corse-eSports** [comment]
Where is it ? 
I don't see , my bad I'm new in programming

**Comment by BossOfGames** [comment]
https://github.com/FSVAOS/VAOS/releases

**Comment by Corse-eSports** [comment]
TThx I downloaded everything , so I just remplace on my ftp ?

**Comment by BossOfGames** [comment]
Basically yes. Just a heads up though, shared hosting (cPanel) is very iffy to support right now. I will get around to a shared hosting version which will work properly on that platform.

**Comment by Corse-eSports** [comment]
Ok thanks , So tar.gz files I run directly on db , and the VAOS-BETA3.zip I put on the FTP with all the hotfix

**Comment by BossOfGames** [comment]
Are you on our discord? It would be easier to talk there. https://discord.gg/4jVzsa

**Comment by Corse-eSports** [comment]
I'm there xD :)
