### ISSUE TITLE
Issue displaying stats

### ISSUE THREAD

**Issue by MrDalle** [FSVAOS/VAOS#59]
Hey!

i like to display the average landing rate also on the dashbaord. We merged oneui with vaos and its working so far but implementing `{{ \App\PIREP::where('user_id', $user->id)->avg('landingrate') }}` or other functions getting an error
![_1ab51cd870088c9359c6ecc434b75542-png](https://user-images.githubusercontent.com/7756672/29006478-2b60732e-7af1-11e7-9b93-fb14982e29a7.jpg)

**Comment by BossOfGames** [comment]
Unless you're sending the `$user` variable to the view in the controller, you need to pull the logged in user. To do so, use the Auth Facade via `Auth::user()->id`

**Comment by MrDalle** [comment]
With the help of Mario i made a new oneuicontroller and store evrything there. A bit more handy then calling `Auth::user()->id`
