### ISSUE TITLE
No Setup File

### ISSUE THREAD

**Issue by 320thSTSMilSim** [FSVAOS/VAOS#60]
Hello, 

Under the installation guide, it says to go to www.YOURSITE.com/setup. I tried going to my site, which is www.bisonairwaysvirtual.com/setup, but it says 404 not found, meaning there isn't a setup file. Any help would be appreciated.

**Comment by BossOfGames** [comment]
Setup is a route built into the system. What you need to do is make sure your web root is set to the VAOS/public folder. That's where the index.php file is stored which is the entry point for the Laravel Application. Try that.

**Comment by 320thSTSMilSim** [comment]
Hmm, i blieve I have it in the public folder. I circled in red. Is that not correct? Or does the domain have to say, www.bisonairwaysvirtual.com/vaos  ?
![bisonairways_vaos](https://user-images.githubusercontent.com/16441364/29049924-9c84f1aa-7b8d-11e7-8537-e9b6e08d6042.png)

**Comment by BossOfGames** [comment]
VAOS Has it's own public folder. Laravel (and subsequently VAOS) are rather complex php applications which don't exactly follow the same drag and drop steps. First off, we need to establish, are you using this as it's own pilot center, or are you putting your entire website on the system (easiest is the later)

**Comment by 320thSTSMilSim** [comment]
Ahh ok, yeah somehow i missed that. I was just thinking of uploading, installing and going. I do have a website I would like to use, but wasn't sure how to integrate it.

**Comment by BossOfGames** [comment]
The best way would be to convert your website into Laravel Blade Templates which is how web pages are displayed. Those are stored in the /resources/views folders and are called up via the routes.

So here's the basic flow

`Send Request to Server -> Web Routes (/routes/web/web.php) -> Controllers -> Blade Template -> Response`

It's a different workflow than a lot of people are used to and can be a little bit overwhelming, however the flexibility are unmatched.

**Comment by BossOfGames** [comment]
It is however advised that you create your own php files inside the /routes/web/ directory as any updates may overwrite your custom routings and.... well... cause issues.
