### ISSUE TITLE
Some Bids don't have a flightnumber

### ISSUE THREAD

**Issue by mfehr94** [FSVAOS/VAOS#71]
Some Bids don't have a flightnumber
[![Screenshot from Gyazo](https://gyazo.com/584b2ddfae2789b15b91e6fdc6d6a336/raw)](https://gyazo.com/584b2ddfae2789b15b91e6fdc6d6a336)

**Comment by mfehr94** [comment]
Schedule Template same, because there is no validation server side.

**Comment by BossOfGames** [comment]
I'm not exactly following. Is it null?

**Comment by mfehr94** [comment]
Empty string

**Comment by BossOfGames** [comment]
Has this issue been resolved? We might want to push this up a release into the 1.0 line.

**Comment by mfehr94** [comment]
on fswire branch yea missing validation on VAOS side

**Comment by BossOfGames** [comment]
Rebuilt a good chuck of the code. Fixed in 2.0
